# Generated by Django 5.0.3 on 2024-04-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_scheduler_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='workDays',
            field=models.JSONField(default=[0]),
            preserve_default=False,
        ),
    ]
