# Generated by Django 5.0.4 on 2024-04-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_scheduler_api', '0003_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_scheduler_api.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicos',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='my_scheduler_api.client'),
            preserve_default=False,
        ),
    ]
