# Generated by Django 5.0.3 on 2024-04-12 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_scheduler_api', '0005_company_remove_servicos_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='company',
            field=models.ForeignKey(default=1   , on_delete=django.db.models.deletion.CASCADE, related_name='services', to='my_scheduler_api.company'),
            preserve_default=False,
        ),
    ]
