# Generated by Django 5.0.3 on 2024-04-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_scheduler_api', '0006_servicos_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='my_scheduler_api.company'),
            preserve_default=False,
        ),
    ]
